name: Continuous Integration
on:
    pull_request:
        branches:
        - main

jobs:
    flutter_test:
        name: Flutter Test and Analyse
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-java@v1
          with:
            java-version: '17.x'
        - uses: subosito/flutter-action@v2
          with:
            channel: 'stable'
        - run: flutter pub get
        - run: flutter analyze
        - run: flutter test

    build_ios:
        name: Build iOS
        needs: [flutter_test]
        runs-on: macos-latest
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-java@v1
          with:
            java-version: '17.x'
        - uses: subosito/flutter-action@v2
          with:
            channel: 'stable'
        - run: flutter pub get
        - run: flutter clean
        - run: flutter build ios --release

    build_android:
        name: Build Android
        needs: [flutter_test]
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-java@v1
          with:
            java-version: '17.x'
        - uses: subosito/flutter-action@v2
          with:
            channel: 'stable'
        - run: flutter pub get
        - run: flutter clean
        - run: flutter build apk --release