name: Continuous Integration
on:
    push:
        branches:
        - master
    pull_request:
        branches:
        - master

jobs:
    flutter_test:
        name: Flutter Test and Analyse
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-java@v1
          with:
            java-version: '17.x'
        - uses: subosito/flutter-action@v2
          with:
            channel: 'stable'
        - run: flutter pub get
        - run: flutter analyze
        - run: flutter test